version: '2'
services:
  docker-mysql-backup-sync-myapp-replica:
    mem_limit: 536870912
    image: myapp/mysqlbackup:latest
    environment:
      sync_freq: 30
      backup_folder: /backups
      backup_type: sync
      db_host: myapp-replica
      db_name: mysql
      db_password: root
      db_user: root
      hostname: dev
      mysql_data_dir: /var/lib/mysql
      s3_access_key: ${S3KEY}
      s3_access_secret: ${S3SECRET}
      s3_bucket: ${S3BUCKET}
      s3_bucket_folder: /myapp_dev
      s3_bucket_location: US
      s3_endpoint: nyc3.digitaloceanspaces.com
    stdin_open: true
    volumes:
    - /home/travis/docker-mysql-backup/dev-log:/var/lib/mysql
    - /home/travis/docker-mysql-backup/entrypoint.sh:/entrypoint.sh
  full:
    image: myapp/mysqlbackup:latest
    environment:
      full_freq: 90
      backup_folder: /backups
      backup_type: full
      db_host: mysql
      db_name: mysql
      db_password: s3cr3t
      db_user: root
      hostname: dev 
      mysql_data_dir: /var/lib/mysql
      s3_access_key: ${S3KEY}
      s3_access_secret: ${S3SECRET}
      s3_bucket: ${S3BUCKET}
      s3_bucket_folder: /myapp_dev
      s3_bucket_location: US
      s3_endpoint: nyc3.digitaloceanspaces.com
    command: sleep 500000
    volumes:
    - /home/travis/docker-mysql-backup/entrypoint.sh:/entrypoint.sh
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3t
